---
title: "Bitácora 2"
format: pdf
editor: source
---

```{r echo=FALSE}
library(readxl)
library(kableExtra)
library(readr)
library(dplyr)
library(janitor) # función clean_names()
library(magrittr) # función %<>%
library(stringr) # función str_replace
library(lubridate)
library(moments) # funciones skewness y kurtosis
library(ggplot2)
```

```{r, echo=F}

# Se carga la base

base <- read_csv("tsa_claims.csv", ) %>%
  na.omit() %>% # Se eliminan NA's
  clean_names()  # Se pasan todos los nombres a minúculas


# Se ajusta el formato de las variables numéricas de montos y de fecha
  
base %<>% mutate_at(c('close_amount', 'claim_amount'),
                    funs(str_remove(., "\\$"))) %>%
  mutate_at(c('close_amount', 'claim_amount'), funs(str_remove(., ";")))  %>%   mutate_at(c('close_amount', 'claim_amount'), funs(as.numeric(.))) %>% mutate(date_received = dmy(date_received))  

attach(base) # Se fijan las variables de la tabla


```

# Ordenamiento de la literatura

```{r, echo=F}

tabla <- read_excel("Archivos auxiliares/Ordenamiento de la literatura.xlsx")

tabla %>%
  kbl(caption = "Ordenamiento de la literautra") %>%
  kable_styling() %>%
  kable_classic_2(full_width = T) %>% 
   row_spec(0, bold = T)

rm(tabla)
```


# Tablas

Cabe mencionar que después de eliminar observaciones con datos desconocidos ($\texttt{NA}$), se cuenta con un total de 94 848 observaciones.


```{r}

medidas <- function(x){
  r <- summary(x) %>% as.vector()
  temp <- data.frame(c(r, sd(x), IQR(x),skewness(x), kurtosis(x)))
  return(temp)
}

nombres <- c("Mínimo",
             "Primer cuartil",
             "Mediana",
             "Media",
             "Tercer cuartil",
             "Máximo",
             "Desviación estándar",
             "Rango intercuartil",
             "Asimetría",
             "Curtosis")

tabla <- medidas(close_amount)
rownames(tabla) <- nombres

tabla %>%
  kbl(caption = "Medidas de resumen", col.names = F) %>%
  kable_styling() %>%
  kable_classic_2(full_width = T) %>% 
   row_spec(0, bold = T)

```



# Gráficos


```{r}
a <- min(year(date_received))
b <- max(year(date_received))

ggplot(base, aes(year(date_received))) +  
  stat_count(geom='bar', aes(y=..count..))+ 
  scale_x_continuous(limits = c(a,b))

```



