---
title: Not used
subtitle: Not used
author:
  - name: Not used
editor: source
format:
  pdf:
    documentclass: scrbook
    classoption: ["onepage", "openany"]
    template-partials:
      - "before-body.tex"
      - "_titlepage.tex" 
    include-in-header: 
      - "in-header.tex"
    toc: true
    lof: true
    lot: true

bibliography: references.bib
---

```{r}
library(ggplot2)
```

# Intro

Según @knuth84 el comportamiento mono sí existe

# Metodología

```{r}
#| label: fig-monos
#| fig-cap: "City and highway mileage for 38 popular models of cars."
#| fig-alt: "Scatterplot of city vs. highway mileage for cars, where points are colored by the number of cylinders. The plot displays a positive, linear, and strong relationship between city and highway mileage, and mileage increases as the number cylinders decreases."
#| fig-width: 6
#| fig-height: 3.5


ggplot(mpg, aes(x = hwy, y = cty, color = cyl)) +
  geom_point(alpha = 0.5, size = 2) +
  scale_color_viridis_c() +
  theme_minimal()

```

La figura @fig-monos muestra un tendencia positiva en el comportamiento mono

# Referencias
